FROM python:3.13.0-alpine3.20
# FROM python:3.9-rc-slim-buster
COPY requeriments.txt .
RUN pip install --no-cache-dir -r requeriments.txt
WORKDIR /app
COPY . .
EXPOSE 5000
CMD ["python", "uber.py"]


# #FROM python:3.14.0rc3-alpine3.22
# #FROM python:3.9-rc-slim-buster
# FROM python:3.13.0-alpine3.20


