POSTGRES_HOST='10.200.0.10'
POSTGRES_PORT=5432
POSTGRES_DB='datauber'
POSTGRES_USER='uber'
export PGPASSWORD='mameluco02'
echo  "psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DB <$1 " 
psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DB <$1 
